In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a3 = np.zeros((2,3))
a3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a4 = np.ones((4,2))
a4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
from IPython.display import display

In [22]:
display(a3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
display(a4)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
a5 = np.linspace(0,1,10)
a5

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
# Dtypes
a5.dtype

dtype('float64')

In [31]:
a5.shape

(10,)

In [32]:
a3.shape

(2, 3)

In [34]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [35]:
np.array_equal(a1D,a2D)

False

In [38]:
# Reshaping
new_dims = (1,a1D.shape[0])
a = a1D.reshape(new_dims)
a.shape

(1, 3)

# Acceso a elementos y Slicing

In [41]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
print(a)

[[ 1  0  3]
 [ 4  3  5]
 [ 6 10 -1]]


In [43]:
a[2,1]

10

In [48]:
a = np.arange(10)
b = np.eye(3)
display(a); display(b)#;para tener 2 comandos en una misma linea 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
a[0:5]

array([0, 1, 2, 3, 4])

In [66]:
b[:,1]#obtener la columna 2 como un vector

array([0., 1., 0.])

In [65]:
b[2,:]#obtener la fila 3 como un vector

array([0., 0., 1.])

In [63]:
b[:,:]#todos los elementos

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Operaciones Aritméticas con Arrays

In [76]:
a = np.arange(4)
print('a   = ', a)
print('a + 5 = ', a+5)
print('a - 5 = ', a-5)
print("a * 2 = ", a*2)
print('a / 2 =', a/2)
print('a // 2 = ', a//2)
print('-a =', -a)
print('a**2 = ', a**2)
print('a % 2 = ',a % 2)

a   =  [0 1 2 3]
a + 5 =  [5 6 7 8]
a - 5 =  [-5 -4 -3 -2]
a * 2 =  [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a // 2 =  [0 0 1 1]
-a = [ 0 -1 -2 -3]
a**2 =  [0 1 4 9]
a % 2 =  [0 1 0 1]


In [69]:
a + a

array([0, 2, 4, 6])

In [70]:
a * a

array([0, 1, 4, 9])

## ufunc

In [79]:
a = np.arange(4)
b = np.arange(1,5)
print(a)
print(b)


[0 1 2 3]
[1 2 3 4]


In [80]:
#np.add               #Suma
#np.substract         #Resta
#np.multiply          #Multiplicar
display(np.exp(a))    #Exponencial
display(np.log(b))    #Logaritmo natural
display(np.sqrt(a))    #Raiz cuadrada
display(np.greater(a,b))    #Superior o igual punto a punto

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

In [84]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i=0
for el in a:
    b[i] = el+el
    i+=1

361 ms ± 8.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [85]:
%%timeit
a+a

561 ns ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Estadística y aleatoridad

In [86]:
#Estadística
a = np.arange(10)

display(np.mean(a))    #promedio
display(np.median(a))  #mediana

4.5

4.5

In [87]:
np.percentile(a,40)     #percentil

3.6

In [88]:
np.random.random(10)    #Aleatoridad

array([0.77072008, 0.11559053, 0.56583975, 0.1583089 , 0.44413065,
       0.60607465, 0.55023241, 0.73812443, 0.49499525, 0.65045762])

pd.read_csv es el metodo que nos permite importar los datos desde un CSV y cargarlo en un **DataFrame**, que es la estructura de base de Pandas